### ISSUE TITLE
Use boolean on the attribute owner

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-bd#101]
The table groupuser is using a tinyint instead of a boolean.

**Comment by razoes** [comment]
I tried but it doesn't assume **boolean**, it changes to **tinyint(1)**.

Did this...
![imagem](https://user-images.githubusercontent.com/19228531/26884709-520e7a62-4b98-11e7-8630-3ee7b6aef9b9.png)

Assumed this...
![imagem](https://user-images.githubusercontent.com/19228531/26884816-a023cd4c-4b98-11e7-8112-d89b1b063323.png)
