### ISSUE TITLE
Procedure addGroupUser should use groupid instead of groupDesc

### ISSUE THREAD

**Issue by migsilva95** [iptomar/projectary-bd#102]

**Comment by asantos3** [comment]
Yup, doing [this](https://github.com/iptomar/projectary-bd/blob/c70b39560ccb2eb783b85c652654d2c4fdb0bf1a/projectary-bd-dump.sql#L394) is unnecessary if you have the groupid in the parameters.

**Comment by razoes** [comment]
It was made that way, but the API team requested that change.
Internally it uses **groupid** but it receives **desc** as param.

**Comment by asantos3** [comment]
This should not be closed, finding the group id via a description is reckless and it should be changed.
Edit: The API is not using it so you can change it without issues.

**Comment by razoes** [comment]
We did as the API team requested. They want to use **description** as input param and the output to be **groupid** if success, else **0**.
They specifically requested it, so they should be using it any time soon. I think @jpcanoso may have something to say about it...

**Comment by asantos3** [comment]
If you have groups with the same description the procedure doesn't work.
Then you limit it to 1 on the select but then you don't don't if you're adding the user to the right group.
It's just reckless and it will have problems, you should change it and the API most use as is, with the groupid.

**Comment by razoes** [comment]
Solved in #104 you cannot have two **groups** with the same **description**.

**Comment by asantos3** [comment]
Just realized that the description is the name of the group... shouldn't have that name but that's another issue.
The unique thing on the table is the id and you should be putting on your wheres a unique field, the description maybe is unique via application logic but not the table itself. What if the requirements change and then the description is no longer unique via the application logic? Everything breaks.

**Comment by asantos3** [comment]
The AS team just told me about the use of the description and it's not unique. The projects can be the same in several years so the teams/groups can have the same name in several years.
Nothing prevents me to not use procedures and circumvent the application logic.

**Comment by razoes** [comment]
One thing is the project's description, the group's description should be unique.

**Comment by asantos3** [comment]
I still think it's reckless to be using a name to find the the groupid instead of just passing the groupid but that's a problem with how the frontend was request to behave.

**Comment by razoes** [comment]
I agree and as I told some comments ago, it was made that way and changed later uppon request.
Did what was requested and tried to shield it as much as I could.
