### ISSUE TITLE
Use the groupid instead of the description in the insertNewGroup

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-bd#106]
This is related to #102 and my [last comment on it](https://github.com/iptomar/projectary-bd/issues/102#issuecomment-306840056):

> The AS team just told me about the use of the description and it's not unique. The projects can be the same in several years so the teams/groups can have the same name in several years.
> Nothing prevents me to not use procedures and circumvent the application logic.

**Comment by razoes** [comment]
The project name (description is the name) may be the same in sevaral years. But that's not the case when we are talking about group's name. Group's name should be unique, there aren't two groups with the same name.
insertNewGroup is to be called and create the group receiving **description** and **password** params, only then a **groupid** is generated, so can't give the procedure a **groupid** param.
As for circumvent the application logic and not use procedures, you can do pretty much anything, even drop a table or the entire schema.

**Comment by asantos3** [comment]
I still think it's reckless to be using a name to find the the groupid instead of just passing the groupid but that's a problem with how the frontend was request to behave.

**Comment by razoes** [comment]
I agree and as I told some comments ago, it was made that way and changed later uppon request.
Did what was requested and tried to shield it as much as I could.
