### ISSUE TITLE
Insert creates gaps on id's column in case of error

### ISSUE THREAD

**Issue by ghost** [iptomar/projectary-bd#107]
It seems id's are still incremented even if the Insert command is not succesfull, leaving gaps in these columns.

Acording to this link, its not a bug: [Bugtracker](https://bugs.mysql.com/bug.php?id=62436).

Still i think it was worth reporting this in case of someone stumbling upon this issue.

Solution:
We could remove the auto increment on those tables and query the MAX id per table and increment that value.
But that would involve both the API and BD groups. 

Or maybe creating a trigger that gets the MAX before insert and updates the id acording to that value. That would only affect the BD group.

**Comment by razoes** [comment]
Is this happening using procedures or trying direct inserts into tables?

**Comment by ghost** [comment]
Direct inserts aswell.

**Comment by razoes** [comment]
What I wanted to know was if using the procedures it occurs. But by your answer I'll assume it does.
Future fix...if we manage to have time to deal with it.

**Comment by ghost** [comment]
Honestly, i dont think its a big deal, its just an id. 
It would probably start causing issues if the field was too small but since the range goes up to 2147483647, meh...
You could pretty much double the number of possible entries by declaring it unsigned since all of them will be positive,

**Comment by razoes** [comment]
Did what you suggested. #112.

**Comment by palfaiate** [comment]
Issue gets sorted out if the newID(table_name) gets used. Implemented since  #114
