### ISSUE TITLE
Desc column on group table should be unique

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-bd#109]
To not allow any duplication of the desc column it should be defined as a unique constraint.

**Comment by razoes** [comment]
It already is.
![imagem](https://user-images.githubusercontent.com/19228531/26903439-0ae6a096-4bd5-11e7-81da-d2d2b8ce29da.png)

**Comment by asantos3** [comment]
I need new glasses, was expecting it to be defined on the same line. Sorry.
