### ISSUE TITLE
Adding a proc that returns a single project info

### ISSUE THREAD

**Issue by ghost** [iptomar/projectary-bd#116]
Is it possible to add a proc like the one that lists all projects but it takes a project id as an aditional parameter and filters the result to only that project?

**Comment by razoes** [comment]
You mean like `SELECT * FROM project p WHERE p.id = projectid`, being `projectid` the param?

**Comment by razoes** [comment]
Added 'projectDetails' procedure in #117 as requested.
Please reopen and give more info if the procedure doesn't match your needs.

**Comment by ghost** [comment]
I was thinking of a proc that lists all active projects or not, like this one [listProjects](https://github.com/iptomar/projectary-bd/blob/master/projectary-bd-dump.sql#L1010) but we would only pass the projectid and the approved parameter.

**Comment by razoes** [comment]
Updated in #118.
If it still doesn't match your needs, please do tell what is the procedure's purpose (I can't see much of a use for it).

**Comment by L0cust** [comment]
Sorry, miscomunication. It was not an aproved project. It was the groups associated to a project, with a application validated or not. We would pass the id of the project and the validation check.

**Comment by ghost** [comment]
Sorry, miscomunication. It was not an aproved project. It was the groups associated to a project, with a application validated or not. We would pass the id of the project and the validation check.

**Comment by razoes** [comment]
Done in #128.
Hope this one matches your needs :)
