### ISSUE TITLE
Phone number length

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-bd#130]
According to [E.164](https://en.wikipedia.org/wiki/E.164) the phone number length should have a maximum of 15 digits. The longest [international call prefix](https://en.wikipedia.org/wiki/List_of_international_call_prefixes), as far as I can tell, is 5 digits. I suggest increasing the length of the phonenumber attribute of the user table to 26 - so we can have some redundancy.

**Comment by razoes** [comment]
Do you mean 20? I don't follow...why 30?

**Comment by asantos3** [comment]
I edited the comment but I recommend 26 so if in the future the lengths are increased we hopefully don't have to change it.

**Comment by razoes** [comment]
Updated in #131.
