### ISSUE TITLE
Remove MD5

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-bd#132]
The database shouldn't do hashing and encryption, it should be done server side, in this case the API.

It should be removed.

**Comment by razoes** [comment]
I'll remove it as soon as the API team agrees with it and do the hashing. Or else meanwhile the passwords would be in plain text.

**Comment by MarkRijckenberg** [comment]
I suggest reading this:

https://en.wikipedia.org/wiki/Secure_Hash_Algorithms

MD5, SHA-0 and SHA1 are all vulnerable to collision attacks.

So if you need to hash, I suggest replacing md5 with sha256 or sha512.

Regards,

Mark Rijckenberg

**Comment by asantos3** [comment]
We know @MarkRijckenberg. This is an unrelated issue.

**Comment by razoes** [comment]
Removed hashing from database in #135 .
Make sure that API does the hashing.
