### ISSUE TITLE
Plain password on groups dump

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-bd#133]
[On the dump you're inserting the groups](https://github.com/iptomar/projectary-bd/blob/8cb1450c1ac5819b62099d91337cdd0628e4c607/projectary-bd-dump.sql#L141) with a plain password, you should use the MD5 hash of it.

**Comment by razoes** [comment]
It is in plain because the **insertNewGroup** does the hashing. This issue depends on #132 change.

**Comment by asantos3** [comment]
You're misunderstanding, you're inserting on the dump in plain text and it stays plain text but when someone inserts via insertNewGroup it hashes it and stores it hashed.

This isn't related to #132, if you hash it on database or api side you need to insert on the dump hashed.

**Comment by razoes** [comment]
I see...you're right. I'll fix it ASAP.

**Comment by razoes** [comment]
Fixed in #134.
