### ISSUE TITLE
InsertNewUser procedure doesn't work proprely

### ISSUE THREAD

**Issue by Freakmania** [iptomar/projectary-bd#33]
CALL InsertNewUser('UserTeste','teste','teste',1,'1')

Error:
Cannot add or update a child row: a foreign key constraint fails (`projectary`.`student`, CONSTRAINT `student_id_fk` FOREIGN KEY (`id`) REFERENCES `entity` (`id`))

**Comment by secprog** [comment]
Fixed by me

**Comment by secprog** [comment]
Está um novo pull request com a correção

**Comment by secprog** [comment]
Reaberto até quem tenha permissão faça merge do pull request

**Comment by palfaiate** [comment]
Procedure Corrected
