### ISSUE TITLE
Attribute change

### ISSUE THREAD

**Issue by razoes** [iptomar/projectary-bd#66]
Change table __project__ attribute __year__ type __year__

To attribute __shoolyear__ type __char(9)__

Like _2016/2017_

**Comment by palfaiate** [comment]
School year should be YEAR(4) because it can be calculated using the starting year

**Comment by razoes** [comment]
The thing is if a user inserts a new project on the second semester the year will be the current year, but if someone inserts a new project before January, the year will be incorrect.

**Comment by razoes** [comment]
Solved. Attribute will remain type YEAR.
