### ISSUE TITLE
Keywords and reserved words

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-bd#68]
Some tables and columns names are using reserved words or keywords.

Tables:
* group (reserved)
* user (keyword)
* type (keyword)

Columns:
* desc (reserved: attribute table, course table, group table and school table)
* password (keyword: group table)
* year (keyword: project table)
* name (keyword: project table)
* value (keyword: projectattribute table)
* password (keyword: user table)

I would suggest renaming at least the table and the column that are reserved words:
* group to team (?)
* desc to description

Source: https://dev.mysql.com/doc/refman/5.5/en/keywords.html

**Comment by razoes** [comment]
You should use it like this:

-  `group`
-  `desc`
-  and so on...

**Comment by asantos3** [comment]
Use the espace character \\ on the \`, like:
> \`group\`

----

I know that but it's not ideal, it would be better to change avoid it all together in my opinion. The change from desc to description is something really simple and should be no trouble.

**Comment by secprog** [comment]
I do not know if it will be critical to change the names right now, so far there was no issue caused by them.
Let the database managers/db developers decide.

**Comment by asantos3** [comment]
There will be issues if reserved words are not escaped properly, we should avoid them if we can.

**Comment by jpcanoso** [comment]
Already happened :)

**Comment by secprog** [comment]
Recently there was a lot of  issues caused by them so reserved words sould be avoided at all cost

**Comment by palfaiate** [comment]
https://dev.mysql.com/doc/refman/5.7/en/keywords.html

**Comment by barcelosrui** [comment]
please don't close a issue when things aren't solved

**Comment by razoes** [comment]
We understand the issue and already talked to several colleagues about it. Much work was done since the database attributes were named. It is now considered to be a step back, to change those names. We suggest that you do use \`**the_attribute_name**\`. We decided that the names are going to stay as they are.
