### ISSUE TITLE
Test accounts not working

### ISSUE THREAD

**Issue by secprog** [iptomar/projectary-bd#69]
With the latest api changes there is the need to change the password of 123qwe to its respective md5 hash 46f94c8de14fb36680850768ff1b7f2a

**Comment by jpcanoso** [comment]
Remember that while we dont have an working e-mail validator the state of locked must be 0 and active must be 1 on the test users.

**Comment by jpcanoso** [comment]
@palfaiate please don't close a issue when things aren't solved

**Comment by palfaiate** [comment]
Active only be 1 after validation.

**Comment by palfaiate** [comment]
Solved in Commit 116a118
