### ISSUE TITLE
You are using systems variables names on database

### ISSUE THREAD

**Issue by barcelosrui** [iptomar/projectary-bd#75]
Please change the name of the database because it gives an error when creating a command to Drop database projectary-master, because "master" is a mysql system variable.

**Comment by asantos3** [comment]
You can use

> drop database \`projectary-master\`

But I agree, something like projectary_master would be better.

**Comment by razoes** [comment]
Much work was done since the database attributes were named. It is now considered to be a step back, to change those names. We suggest that you do as @asantos3 said and use \`projectary-master\`
