### ISSUE TITLE
Missing Attributes in Users

### ISSUE THREAD

**Issue by barcelosrui** [iptomar/projectary-bd#77]
Please add the following attributes in the database:
![image](https://cloud.githubusercontent.com/assets/26029476/25976967/fc2c48a6-36af-11e7-9479-c1da212c16c9.png)

**Comment by secprog** [comment]
You sould be more watchful there is a struture to save that attributes

--
-- Table structure for table `userattribute`
--

DROP TABLE IF EXISTS `userattribute`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `userattribute` (
  `userid` int(11) NOT NULL,
  `attributeid` int(11) NOT NULL,
  `value` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`userid`,`attributeid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

**Comment by barcelosrui** [comment]
Now I realize, so try to work on the "API" that would like to work on "Frontend" in the "Create User" part.

**Comment by secprog** [comment]
This sould be review by DBA/DB Devs, i think that is not the best way to do this, it will appear crazy joins on selects and will be more hard when inserting new data. Yes i tried it crazy stuff will appear

**Comment by razoes** [comment]
In my opinion, **users** table should have all the needed attributes and they should be required, leaving no place for an extra **userattribute** table. We should 
But this seems to have been discussed on May 5th night's class, wich I didn't attend.

**Comment by razoes** [comment]
In my opinion, **users** table should have all the needed attributes and they should be required, leaving no place for an extra **userattribute** table.
But this seems to have been discussed on May 5th night's class, wich I didn't attend.

**Comment by secprog** [comment]
I have no idea if it has or not discussed but i aggre with @razoes

**Comment by palfaiate** [comment]
Fields can be added using userattribute table. It as been made available since 91200e9
