### ISSUE TITLE
Please insert data into the database

### ISSUE THREAD

**Issue by diogosantosmendes** [iptomar/projectary-bd#80]
* It is necessary to populate the database with records in all tables.
* The records to insert must be several and not all with the same value in certain attributes (eg user.isadmin).
* The attribute "active" at table "user" must be "1".
* The users password must be coded in md5 (eg "123qwe" -> "46f94c8de14fb36680850768ff1b7f2a").

PS. Remember that this data is only valid during the development of the system, we need to see things working

**Comment by secprog** [comment]
It is missing too the attribute public in user table (attribute used to set visibility of profile)

**Comment by secprog** [comment]
It is needed too a new attribute "token" in the user table. If not = NO PASSWORD RECOVERY

**Comment by palfaiate** [comment]
Solved in Commit 116a118
