### ISSUE TITLE
Admin on the type table

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-bd#90]
@luisnunes111 Put an interesting question. Why don't have an admin type and eliminate the need for a isadmin column?

**Comment by razoes** [comment]
Because a teacher may be an admin or not. If admin was a type, a user couldn't be both at the same time.

**Comment by asantos3** [comment]
Doesn't the admin supersedes the teacher? That would mean that it has access to the teacher functionality.

**Comment by razoes** [comment]
Eventually...it could well be like you say.
But I wouldn't change it now. There are many procedures involved, and they would all have to be updated.
Unless it is critical, I would leave it as is.

**Comment by asantos3** [comment]
Agreed.
