### ISSUE TITLE
Procedure descExists does not work with special characters

### ISSUE THREAD

**Issue by Freakmania** [iptomar/projectary-bd#91]

**Comment by razoes** [comment]
I'm not sure how you tried it, and I'm not saying your wrong, but the way I tried it works just fine.
The table **group** has an entry with the **desc** value *chouriças*.
I tried *chouricas*, *chouriÇas* and *chouriças*, as you can see, only the last one returns **true**.

![imagem](https://cloud.githubusercontent.com/assets/19228531/26749464/234c5282-4803-11e7-951b-241384b82e84.png)

If the issue persists, please feel free to reopen it and give some additional info about it.
